export const AUTH_SET_USER_NAME = 'AUTH_SET_USER_NAME'
export const AUTH_SET_CLIENT_ID = 'AUTH_SET_CLIENT_ID'

export const APP_FETCH_USER_DATA = 'APP_FETCH_USER_DATA'
export const APP_SET_USER_DATA = 'APP_SET_USER_DATA'
